name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install Cy2
        run: npm install -g cy2
      - name: Set api url
        run: export CYPRESS_API_URL="https://sorry-cypress-demo-director.herokuapp.com/"
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          command: npm start
                     
          
  cypress-run2:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install Cy2
        run: npm install -g cy2
      - name: Set api url
        run: export CYPRESS_API_URL="https://sorry-cypress-demo-director.herokuapp.com/"
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          command: npm start
